[2024-10-12T18:19:27.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T18:19:27.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-12T18:19:09.616001+00:00 [queued]>
[2024-10-12T18:19:27.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-12T18:19:09.616001+00:00 [queued]>
[2024-10-12T18:19:27.096+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-10-12T18:19:27.105+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-10-12 18:19:09.616001+00:00
[2024-10-12T18:19:27.120+0000] {standard_task_runner.py:64} INFO - Started process 259 to run task
[2024-10-12T18:19:27.124+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_experiment', 'train_and_log_model', 'manual__2024-10-12T18:19:09.616001+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmp7i9um39h']
[2024-10-12T18:19:27.127+0000] {standard_task_runner.py:91} INFO - Job 97: Subtask train_and_log_model
[2024-10-12T18:19:27.183+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-12T18:19:09.616001+00:00 [running]> on host bfabb847763f
[2024-10-12T18:19:27.260+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_experiment' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T18:19:09.616001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-12T18:19:09.616001+00:00'
[2024-10-12T18:19:27.261+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T18:19:27.276+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-2 with path datasets/prepared_data.csv
[2024-10-12T18:19:27.283+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-12T18:19:27.284+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-12T18:19:27.819+0000] {logging_mixin.py:188} INFO - result1
[2024-10-12T18:19:27.876+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:27 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-12T18:19:45.129+0000] {logging_mixin.py:188} INFO - result2 random_forest
[2024-10-12T18:19:54.459+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:54 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
[2024-10-12T18:19:54.509+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:54 INFO mlflow.tracking._tracking_service.client: üèÉ View run random_forest_run at: http://mlflow-service:5000/#/experiments/152697137012865863/runs/6f73a4e174d74566898d42dad02d3ccc.
[2024-10-12T18:19:54.510+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:54 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/152697137012865863.
[2024-10-12T18:19:54.543+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:54 INFO mlflow.tracking._tracking_service.client: üèÉ View run @GodSiemens at: http://mlflow-service:5000/#/experiments/152697137012865863/runs/e55e4b39d0694eb2b944ee5698f53f3a.
[2024-10-12T18:19:54.546+0000] {logging_mixin.py:188} WARNING - 2024/10/12 18:19:54 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/152697137012865863.
[2024-10-12T18:19:54.553+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T18:19:54.556+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/HW2.py", line 113, in train_and_log_model
    eval_results = mlflow.evaluate(
  File "/home/airflow/.local/lib/python3.10/site-packages/mlflow/models/evaluation/base.py", line 1531, in evaluate
    raise MlflowException(
mlflow.exceptions.MlflowException: The model argument must be a string URI referring to an MLflow model, an MLflow Deployments endpoint URI, an instance of `mlflow.pyfunc.PyFuncModel`, a function, or None.
[2024-10-12T18:19:54.603+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Nikita_Lapshin_experiment, task_id=train_and_log_model, run_id=manual__2024-10-12T18:19:09.616001+00:00, execution_date=20241012T181909, start_date=20241012T181927, end_date=20241012T181954
[2024-10-12T18:19:54.625+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 97 for task train_and_log_model (The model argument must be a string URI referring to an MLflow model, an MLflow Deployments endpoint URI, an instance of `mlflow.pyfunc.PyFuncModel`, a function, or None.; 259)
[2024-10-12T18:19:54.703+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-12T18:19:54.758+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T18:19:54.760+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
