[2024-10-13T23:27:25.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-13T23:27:25.575+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-13T23:23:25.241644+00:00 [queued]>
[2024-10-13T23:27:25.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-13T23:23:25.241644+00:00 [queued]>
[2024-10-13T23:27:25.587+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-10-13T23:27:25.618+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-10-13 23:23:25.241644+00:00
[2024-10-13T23:27:25.650+0000] {standard_task_runner.py:64} INFO - Started process 453 to run task
[2024-10-13T23:27:25.654+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_experiment', 'train_and_log_model', 'manual__2024-10-13T23:23:25.241644+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmpdqk2afr3']
[2024-10-13T23:27:25.662+0000] {standard_task_runner.py:91} INFO - Job 132: Subtask train_and_log_model
[2024-10-13T23:27:25.802+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_experiment.train_and_log_model manual__2024-10-13T23:23:25.241644+00:00 [running]> on host e332dadfa0c1
[2024-10-13T23:27:25.922+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_experiment' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-13T23:23:25.241644+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-13T23:23:25.241644+00:00'
[2024-10-13T23:27:25.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-13T23:27:25.951+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-2 with path datasets/prepared_data.csv
[2024-10-13T23:27:25.962+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-13T23:27:25.965+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-13T23:27:30.822+0000] {logging_mixin.py:188} INFO - result1
[2024-10-13T23:27:31.031+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:27:31 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-10-13T23:27:52.636+0000] {logging_mixin.py:188} INFO - result2 random_forest
[2024-10-13T23:28:03.300+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2024-10-13T23:28:13.301+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:13 WARNING mlflow.models.model: Input example should be provided to infer model signature if the model signature is not provided when logging the model.
[2024-10-13T23:28:28.099+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-13T23:28:28.152+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-13T23:28:29.525+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-13T23:28:30.610+0000] {connectionpool.py:331} WARNING - Connection pool is full, discarding connection: storage.yandexcloud.net. Connection pool size: 10
[2024-10-13T23:28:33.337+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-13T23:28:34.491+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:34 INFO mlflow.data.evaluation_dataset: Cannot convert input data to `evaluate()` to an mlflow dataset, input must be a list, a numpy array, a panda Dataframe or a spark Dataframe, but received <class 'tuple'>.
[2024-10-13T23:28:34.563+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:34 INFO mlflow.tracking._tracking_service.client: üèÉ View run random_forest_run at: http://mlflow-service:5000/#/experiments/889983933329739548/runs/990548ed5421414293af167dbdf472aa.
[2024-10-13T23:28:34.563+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:34 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/889983933329739548.
[2024-10-13T23:28:34.624+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:34 INFO mlflow.tracking._tracking_service.client: üèÉ View run @GodSiemens at: http://mlflow-service:5000/#/experiments/889983933329739548/runs/3747af0322064420b9f74b463e5d9538.
[2024-10-13T23:28:34.625+0000] {logging_mixin.py:188} WARNING - 2024/10/13 23:28:34 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow-service:5000/#/experiments/889983933329739548.
[2024-10-13T23:28:34.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-13T23:28:34.647+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/HW2.py", line 119, in train_and_log_model
    eval_results = mlflow.evaluate(
  File "/home/airflow/.local/lib/python3.10/site-packages/mlflow/models/evaluation/base.py", line 1598, in evaluate
    dataset = EvaluationDataset(
  File "/home/airflow/.local/lib/python3.10/site-packages/mlflow/data/evaluation_dataset.py", line 402, in __init__
    raise MlflowException(
mlflow.exceptions.MlflowException: The data argument must be a numpy array, a list or a Pandas DataFrame, or spark DataFrame if pyspark package installed.
[2024-10-13T23:28:34.707+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Nikita_Lapshin_experiment, task_id=train_and_log_model, run_id=manual__2024-10-13T23:23:25.241644+00:00, execution_date=20241013T232325, start_date=20241013T232725, end_date=20241013T232834
[2024-10-13T23:28:34.765+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 132 for task train_and_log_model (The data argument must be a numpy array, a list or a Pandas DataFrame, or spark DataFrame if pyspark package installed.; 453)
[2024-10-13T23:28:34.890+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-13T23:28:34.986+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T23:28:34.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
