[2024-10-13T04:42:39.795+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-13T04:42:39.811+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-12T01:00:00+00:00 [queued]>
[2024-10-13T04:42:39.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-12T01:00:00+00:00 [queued]>
[2024-10-13T04:42:39.828+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-10-13T04:42:39.847+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2024-10-12 01:00:00+00:00
[2024-10-13T04:42:39.860+0000] {standard_task_runner.py:64} INFO - Started process 5966 to run task
[2024-10-13T04:42:39.870+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Nikita_Lapshin_experiment', 'train_and_log_model', 'scheduled__2024-10-12T01:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/HW2.py', '--cfg-path', '/tmp/tmpuyokb86c']
[2024-10-13T04:42:39.877+0000] {standard_task_runner.py:91} INFO - Job 114: Subtask train_and_log_model
[2024-10-13T04:42:39.945+0000] {task_command.py:426} INFO - Running <TaskInstance: Nikita_Lapshin_experiment.train_and_log_model scheduled__2024-10-12T01:00:00+00:00 [running]> on host 56b144d03b9f
[2024-10-13T04:42:40.010+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lapshin Nikita' AIRFLOW_CTX_DAG_ID='Nikita_Lapshin_experiment' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2024-10-12T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-12T01:00:00+00:00'
[2024-10-13T04:42:40.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-13T04:42:40.025+0000] {s3.py:1422} INFO - Downloading source S3 file from Bucket mlops-2 with path datasets/prepared_data.csv
[2024-10-13T04:42:40.032+0000] {base.py:84} INFO - Using connection ID 's3_connection' for task execution.
[2024-10-13T04:42:40.033+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='s3_connection', conn_type='aws') credentials retrieved from login and password.
[2024-10-13T04:42:40.259+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-13T04:42:40.260+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/HW2.py", line 89, in train_and_log_model
    data = pd.read_csv(s3_hook.download_file(prepared_path, bucket_name=BUCKET))
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1432, in download_file
    raise e
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1425, in download_file
    s3_obj = self.get_key(key, bucket_name)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 158, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 132, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 965, in get_key
    obj.load(**sanitize_extra_args())
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/resources/factory.py", line 565, in do_action
    response = action(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-10-13T04:42:40.280+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Nikita_Lapshin_experiment, task_id=train_and_log_model, run_id=scheduled__2024-10-12T01:00:00+00:00, execution_date=20241012T010000, start_date=20241013T044239, end_date=20241013T044240
[2024-10-13T04:42:40.289+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 114 for task train_and_log_model (An error occurred (403) when calling the HeadObject operation: Forbidden; 5966)
[2024-10-13T04:42:40.303+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-13T04:42:40.321+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-13T04:42:40.322+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
